# Use the official Apache HTTP Server image from the Docker Hub
FROM httpd:2.4

# Copy the custom HTML file to the Apache web server's document root
COPY ./index.html /usr/local/apache2/htdocs/

# Expose port 80
EXPOSE 80
